# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d7VKksGm7ZYIhaLK058iceq_RIil_hdN

## Aula 03
- Embeddings
- Distância Euclidiana
- Distância de Cosseno

É Nescessario dar "Run" em cada bloco de código para que as funções fiquem disponiveis!
"""

# Imports

from google.colab import userdata
import requests
import math

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

import numpy as np
import pandas as pd

import re
import spacy

"""## Criação da função get_embedings
- Checa se a chave OPENROUTER_API_KEY existe
- É preciso fazer a configuração da mesma no Colab
"""

# Checa se tem a API KEY
openrouter_api_key = userdata.get('OPENROUTER_API_KEY')

# Se não solta um erro
if not openrouter_api_key:
  raise ValueError("OPENROUTER_API_KEY is not set in Colab secrets.")

def get_embeddings(text):
  response = requests.post(
      "https://openrouter.ai/api/v1/embeddings",
  headers={
    "Authorization": f"Bearer {openrouter_api_key}",
    "Content-Type": "application/json",
  },
  json={
    "model": "openai/text-embedding-3-small",
    "input": f"{text}"
  }
  )

  data = response.json()
  embedding = data["data"][0]["embedding"]

  print(f"Embedding dimension: {len(embedding)}")
  print(embedding)
  return embedding, data

# Testando se está funcionando
#get_embeddings("The quick brown fox jumps over the lazy dog")

"""## Criação da função distancia_euclidiana, sem utilizar bibliotecas externas, para explicar oque está sendo feito."""

def distancia_euclidiana(vetor1, vetor2):
    soma_quadrados = sum((a - b) ** 2 for a, b in zip(vetor1, vetor2))
    return math.sqrt(soma_quadrados)

"""## Criação da função distancia_cosseno, sem utilizar bibliotecas externas, para explicar oque está sendo feito."""

def distancia_cosseno(vetor1, vetor2):
    produto_escalar = sum(a * b for a, b in zip(vetor1, vetor2))

    magnitude1 = math.sqrt(sum(a ** 2 for a in vetor1))
    magnitude2 = math.sqrt(sum(b ** 2 for b in vetor2))

    if magnitude1 == 0 or magnitude2 == 0:
        return 1.0

    similaridade = produto_escalar / (magnitude1 * magnitude2)
    return 1.0 - similaridade

"""Similaridade de Cosseno"""

def similaridade_cosseno(vec1: np.ndarray, vec2: np.ndarray) -> float:
    norm_v1 = np.linalg.norm(vec1)
    norm_v2 = np.linalg.norm(vec2)
    if norm_v1 == 0 or norm_v2 == 0:
        return 0.0
    return float(np.dot(vec1, vec2) / (norm_v1 * norm_v2))

"""## Testando com os dados fornecidos"""

dados_categorias = {
    "animal": ["gato", "felino", "cachorro"],
    "veiculo": ["carro", "caminhão", "moto"],
    "fruta": ["banana", "maçã", "goiaba"]
}

# 1. Obter primeiro os embeddings dos temas/âncoras
banco_temas = {}
for tema in dados_categorias.keys():
    print(f"Buscando embedding do tema: {tema}...")
    embedding_tema, _ = get_embeddings(tema)
    banco_temas[tema] = embedding_tema

# 2. Processar cada palavra e calcular as métricas
lista_resultados = []

for tema, palavras in dados_categorias.items():
    vetor_tema = banco_temas[tema]

    for palavra in palavras:
        print(f"Processando palavra: {palavra}...")
        vetor_palavra, _ = get_embeddings(palavra)

        # Cálculos de distância da palavra contra o seu tema
        dist_euclidiana = distancia_euclidiana(vetor_palavra, vetor_tema)
        dist_cosseno = distancia_cosseno(vetor_palavra, vetor_tema)

        # Salva os dados estruturados (guardamos apenas o tamanho do embedding para visualização na tabela)
        lista_resultados.append({
            "Tema": tema,
            "Palavra": palavra,
            "Dimensão Embedding": len(vetor_palavra),
            "Distância Euclidiana": round(dist_euclidiana, 4),
            "Distância de Cosseno": round(dist_cosseno, 4)
        })

# --- Geração da Tabela ---
df = pd.DataFrame(lista_resultados)

# Exibe a tabela formatada no ambiente do Colab
print("\n--- TABELA DE DISTÂNCIAS POR TEMA ---")
display(df)

"""## Geração de Grafico dos embeddings"""

# Extrair as palavras e os vetores na mesma ordem
labels = list(banco_embeddings.keys())
vetores = list(banco_embeddings.values())

# Reduz a dimensão dos embeddings usando PCA
pca = PCA(n_components=2)
vetores_2d = pca.fit_transform(vetores)

plt.figure(figsize=(10, 7))

# Plota os pontos
plt.scatter(vetores_2d[:, 0], vetores_2d[:, 1], color='dodgerblue', edgecolors='k', s=120)

# Adiciona o texto de cada palavra ao lado do seu ponto
for i, palavra in enumerate(labels):
    plt.annotate(
        palavra,
        (vetores_2d[i, 0], vetores_2d[i, 1]),
        textcoords="offset points",
        xytext=(8, 5),
        ha='center',
        fontsize=10,
        fontweight='bold'
    )

# Estilização do gráfico
plt.title("Visualização Espacial das similaridades", fontsize=14, fontweight='bold')
plt.xlabel("Componente 1", fontsize=11)
plt.ylabel("Componente 2", fontsize=11)
plt.grid(True, linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

"""Agora testando a comparação com frases"""

# Pode realizar mais testes mudando a frase ancora para uma negação, ou as frases de comparação

frase_ancora = "O cachorro correu no parque e brincou com a bola."

frases_comparacao = [
    ("Similar (mesmo sentido, palavras diferentes)", "Um cão estava correndo no jardim e brincando com seu brinquedo."),
    ("Relacionado (mesmo contexto de animais)", "O gato dormiu na almofada da sala durante toda a tarde."),
    ("Diferente (outro domínio - economia)", "A taxa de juros do banco central subiu dois pontos percentuais."),
    ("Oposto/Negação", "Nenhum animal esteve no parque e o cão permaneceu preso em casa.")
]

embedding_ancora, _ = get_embeddings(frase_ancora)
vec_ancora = np.array(embedding_ancora, dtype=np.float32)

vecs_comp = []
for _, frase_texto in frases_comparacao:
    embedding_result, _ = get_embeddings(frase_texto)
    vecs_comp.append(np.array(embedding_result, dtype=np.float32))

resultados = []
for i, (tipo_frase, texto_frase) in enumerate(frases_comparacao):
    vec = vecs_comp[i]
    resultados.append({
        "Texto": tipo_frase,
        "Frase Original": texto_frase,
        "Dist. Euclidiana": round(distancia_euclidiana(vec_ancora, vec), 4),
        "Similaridade Cosseno": round(similaridade_cosseno(vec_ancora, vec), 4),
        "Distância Cosseno": round(distancia_cosseno(vec_ancora, vec), 4)
    })

df_resultados = pd.DataFrame(resultados)
df_resultados

"""## Busca Semântica Simples Manual (Embedding por Embedding)

A Busca Semântica substitui a busca simples por palavra-chave .

Nesta etapa:

1. Lemos os arquivos de markdown gerados na aula 2.
2. Separamos o texto linha por linha.
3. Geramos o embedding para cada linha.
4. Definimos uma pergunta (*query*) de busca. (O que é “**Autonomia e opacidade algorítmica**”?, O que é o diário de bordo da IA? e etc)
5. Geramos o embedding da query e calculamos a Similaridade de Cosseno contra cada trecho.
6. Retornamos o TOP 3 com maior score!
7. Dividir os documentos agora por trechos maiores (parágrafo) e repetir a etapa anterior.
8. Dividir os documentos agora por trechos maiores (capitulos) e repetir a etapa anterior.
"""

nlp = spacy.load("en_core_web_sm")

with open("/content/sample_data/bioetica_e_ia.md","r",encoding="utf-8") as file:
    text = file.read()

# Remove HTML comments
text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)
# Remove Markdown headings:
text = re.sub(r'^#+.*$', '', text, flags=re.MULTILINE)
# Remove lines containing only numbers:
text = re.sub(r'^\s*\d+\s*$', '', text, flags=re.MULTILINE)
# Fix words broken by PDF extraction:
text = re.sub(r'(\w+)\s+-\s+(\w+)', r'\1\2', text)
text = re.sub(r'\n+', '\n', text)
text = text.strip()

doc = nlp(text)

sentences = [
    sent.text.strip()
    for sent in doc.sents
    if sent.text.strip()
]

first_5_sentences = sentences[:5]
print(first_5_sentences)

for sentence in sentences[:5]:
    print(sentence)

#print(f"Found {len(sentences)} sentences.\n")

#for i, sentence in enumerate(sentences, start=1):
#    print(f"{i}: {sentence}")

# Reptindo código anterio para caso queira testar separadamente
# mantendo o teste com apenas 3 sentenças

frase_ancora = "Medicina no ambito moderno"

frases_comparacao = sentences[:3]

for frase in frases_comparacao:
    print(frase)

embedding_ancora, _ = get_embeddings(frase_ancora)
vec_ancora = np.array(embedding_ancora, dtype=np.float32)

vecs_comp = []
for frase_texto in frases_comparacao:
    embedding_result, _ = get_embeddings(frase_texto)
    vecs_comp.append(np.array(embedding_result, dtype=np.float32))

resultados = []
for i, texto_frase in enumerate(frases_comparacao):
    vec = vecs_comp[i]
    resultados.append({
        "Texto": texto_frase,
        "Frase Original": texto_frase,
        "Dist. Euclidiana": round(distancia_euclidiana(vec_ancora, vec), 4),
        "Similaridade Cosseno": round(similaridade_cosseno(vec_ancora, vec), 4),
        "Distância Cosseno": round(distancia_cosseno(vec_ancora, vec), 4)
    })

df_resultados = pd.DataFrame(resultados)
df_resultados